import type { IFieldDefinitionRepository } from '../../../contracts/field-definition.repository.contract.js'

const SYSTEM_FIELDS = [
  // games
  { name: 'Plataforma', fieldKey: 'platform', fieldType: 'select' as const, collectionType: 'games' as const, selectOptions: ['PS1', 'PS2', 'PS3', 'PS4', 'PS5', 'Xbox', 'Xbox 360', 'Xbox One', 'Xbox Series', 'Nintendo Switch', 'PC', 'Mobile', 'Outro'], isSystem: true, userId: null },
  { name: 'Gênero', fieldKey: 'genre', fieldType: 'select' as const, collectionType: 'games' as const, selectOptions: [
    'Ação',
    'Ação-Aventura',
    'Aventura',
    'Battle Royale',
    'Corrida',
    'Esportes',
    'Estratégia',
    'FPS',
    'Indie',
    'Luta',
    'MMORPG',
    'MOBA',
    'Metroidvania',
    'Mundo Aberto',
    'Plataforma',
    'Puzzle',
    'RPG',
    'Roguelike',
    'Simulação',
    'Souls-like',
    'Survival Horror',
    'Terror',
    'Outro',
  ], isSystem: true, userId: null },
  { name: 'Ano de lançamento', fieldKey: 'release_year', fieldType: 'number' as const, collectionType: 'games' as const, selectOptions: null, isSystem: true, userId: null },
  { name: 'Desenvolvedor', fieldKey: 'developer', fieldType: 'text' as const, collectionType: 'games' as const, selectOptions: null, isSystem: true, userId: null },
  { name: 'Status', fieldKey: 'status', fieldType: 'select' as const, collectionType: 'games' as const, selectOptions: ['Na fila', 'Em andamento', 'Zerado', 'Platinado'], isSystem: true, userId: null },
  { name: 'Data que zerou', fieldKey: 'completion_date', fieldType: 'date' as const, collectionType: 'games' as const, selectOptions: null, isSystem: true, userId: null },
  { name: 'Steam App ID', fieldKey: 'steam_appid', fieldType: 'number' as const, collectionType: 'games' as const, selectOptions: null, isSystem: true, isHidden: true, userId: null },
  { name: 'Tempo jogado (min)', fieldKey: 'playtime_minutes', fieldType: 'number' as const, collectionType: 'games' as const, selectOptions: null, isSystem: true, userId: null },

  // books
  { name: 'Autor', fieldKey: 'author', fieldType: 'text' as const, collectionType: 'books' as const, selectOptions: null, isSystem: true, userId: null },
  { name: 'Editora', fieldKey: 'publisher', fieldType: 'text' as const, collectionType: 'books' as const, selectOptions: null, isSystem: true, userId: null },
  { name: 'Ano de publicação', fieldKey: 'publication_year', fieldType: 'number' as const, collectionType: 'books' as const, selectOptions: null, isSystem: true, userId: null },
  { name: 'Gênero', fieldKey: 'genre', fieldType: 'select' as const, collectionType: 'books' as const, selectOptions: [
    'Aventura',
    'Autoajuda',
    'Autobiografia',
    'Biografia',
    'Clássico',
    'Crônica',
    'Drama',
    'Educacional',
    'Fantasia',
    'Ficção',
    'Ficção Científica',
    'Filosofia',
    'História',
    'HQ / Quadrinhos',
    'Infantojuvenil',
    'Mangá',
    'Mistério',
    'Não-ficção',
    'Negócios',
    'Poesia',
    'Psicologia',
    'Religião',
    'Romance',
    'Suspense',
    'Tecnologia',
    'Terror',
    'Outro',
  ], isSystem: true, userId: null },
  { name: 'Número de páginas', fieldKey: 'page_count', fieldType: 'number' as const, collectionType: 'books' as const, selectOptions: null, isSystem: true, userId: null },
  { name: 'ISBN', fieldKey: 'isbn', fieldType: 'text' as const, collectionType: 'books' as const, selectOptions: null, isSystem: true, userId: null },
  { name: 'Status', fieldKey: 'status', fieldType: 'select' as const, collectionType: 'books' as const, selectOptions: ['Quero ler', 'Lendo', 'Lido'], isSystem: true, userId: null },

  // cardgames
  { name: 'Jogo base', fieldKey: 'game_base', fieldType: 'select' as const, collectionType: 'cardgames' as const, selectOptions: ['Magic', 'Pokémon', 'Yu-Gi-Oh', 'Outro'], isSystem: true, userId: null },
  { name: 'Raridade', fieldKey: 'rarity', fieldType: 'text' as const, collectionType: 'cardgames' as const, selectOptions: null, isSystem: true, userId: null },
  { name: 'Condição', fieldKey: 'condition', fieldType: 'select' as const, collectionType: 'cardgames' as const, selectOptions: ['Mint', 'Near Mint', 'Played'], isSystem: true, userId: null },
  { name: 'Quantidade', fieldKey: 'quantity', fieldType: 'number' as const, collectionType: 'cardgames' as const, selectOptions: null, isSystem: true, userId: null },

  // boardgames
  { name: 'Editora', fieldKey: 'publisher', fieldType: 'text' as const, collectionType: 'boardgames' as const, selectOptions: null, isSystem: true, userId: null },
  { name: 'Ano', fieldKey: 'release_year', fieldType: 'number' as const, collectionType: 'boardgames' as const, selectOptions: null, isSystem: true, userId: null },
  { name: 'Jogadores (mín)', fieldKey: 'min_players', fieldType: 'number' as const, collectionType: 'boardgames' as const, selectOptions: null, isSystem: true, userId: null },
  { name: 'Jogadores (máx)', fieldKey: 'max_players', fieldType: 'number' as const, collectionType: 'boardgames' as const, selectOptions: null, isSystem: true, userId: null },
  { name: 'Tempo de partida (min)', fieldKey: 'play_time', fieldType: 'number' as const, collectionType: 'boardgames' as const, selectOptions: null, isSystem: true, userId: null },
  { name: 'Gênero/Mecânica', fieldKey: 'genre', fieldType: 'select' as const, collectionType: 'boardgames' as const, selectOptions: [
    'Abstrato',
    'Ameritrash',
    'Area Control',
    'Card Game',
    'Cooperativo',
    'Crianças',
    'Deck-builder',
    'Dexterity',
    'Dice-builder',
    'Engine Builder',
    'Eurogame',
    'Família',
    'Festa / Party',
    'Hidden Movement',
    'Legacy / Campanha',
    'Living Card Game',
    'Negociação',
    'Push Your Luck',
    'Roll-and-write',
    'RPG',
    'Solo',
    'Tile Placement',
    'Trivia',
    'Wargame',
    'Worker Placement',
    'Outro',
  ], isSystem: true, userId: null },
  { name: 'Status', fieldKey: 'status', fieldType: 'select' as const, collectionType: 'boardgames' as const, selectOptions: ['Tenho', 'Quero', 'Emprestado'], isSystem: true, userId: null },
]

export async function seedFieldDefinitions(repo: IFieldDefinitionRepository): Promise<void> {
  for (const field of SYSTEM_FIELDS) {
    await repo.upsertSystem(field)
  }
}
